Fixing bug with exceptions. Added getLiquidPart() and getGasPart() to SteamCalculator for saturation props in saturated region. Adding case for Borland compiler in isinfnan (still doesn't build on BCB5.5 though). Changed some parameters in units.h to 'const double &'. Removed some missing 'inline' declarations in steamproperty.h. Implemented SCons testing of 'units.h' in 'ctest' directory.

diff --git a/trunk/freesteam/ctest/Makefile b/trunk/freesteam/ctest/Makefile
--- a/trunk/freesteam/ctest/Makefile
+++ b/trunk/freesteam/ctest/Makefile
@@ -15,9 +15,69 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 
-PACKAGE_ROOT = ..
+CPASS = $(wildcard *.cpass.cpp)
+CFAIL = $(wildcard *.cfail.cpp)
 
-include ../make-common.mak
-include make-ctest.mak
+EXE_SUFFIX = .exe
 
 all: ctest
+
+-include $(CPASS:.cpp=.d)
+-include $(CFAIL:.cpp=.d)
+
+LIB = ../libfreesteam.a
+
+#--------------------------
+# COMPILE-TIME TESTING
+
+.PHONY: ctest cpasstest cfailtest ctestheading do_ctest
+
+CPASSEXES = $(CPASS:.cpp=$(EXE_SUFFIX) )
+CFAILOKS = $(CFAIL:.cpp=.ok )
+
+ctest: $(LIB) ctestheading do_ctest
+
+do_ctest:
+	@if [ -f ctest.skip ]; then echo "Skipping ('rm ctest.skip' to force compile-time tests)"; echo; exit 0; fi; \
+	echo "Running compile-time tests... ('touch ctest.skip' to skip these tests)"; \
+	make $(CPASSEXES) $(CFAILOKS); \
+	echo \
+	echo "COMPILE-TIME TESTS SUCCEEDED!" \
+	echo \
+
+ctestheading:
+	@echo
+	@echo "COMPILE-TIME TESTING"
+	@echo
+
+%.cpass$(EXE_SUFFIX): %.cpass.cpp $(LIB) Makefile
+	@echo "ctest $< (expect pass)..."
+	@echo $(CXX) -DCTEST $< $(LIB) -o $@ $(LDFLAGS);
+	@if $(CXX) -DCTEST $< $(LIB) -o $@ $(LDFLAGS); then exit 0; \
+	else \
+	  echo; \
+	  echo "$<:1: CTEST FAIL: Expected to compile, but did not."; \
+	  echo; \
+	  exit 1; \
+	fi;
+
+%.cfail.ok: %.cfail.cpp $(LIB) Makefile
+	@echo "ctest $< (expect fail)..."
+	@echo $(CXX) -DCTEST $< $(LIB) -o cfail$(EXE_SUFFIX) $(LDFLAGS)
+	@if $(CXX) -DCTEST $< $(LIB) -o cfail$(EXE_SUFFIX) $(LDFLAGS); then \
+	  echo; \
+	  echo "$<:1: CTEST FAIL: Shouldn't have compiled, but did."; \
+	  echo; \
+	  if [ -f $@ ]; then rm cfail$(EXE_SUFFIX); fi; \
+	  exit 1; \
+	fi; \
+	echo "$<" > $@;
+
+#---------------------------------------------------------
+# CLEAN
+
+clean:
+	@-rm *.o *.d.* $(CFAILOKS) $(CPASSEXES) *.stackdump
+
+distclean: clean
+	@-rm *.d
